#!/bin/sh


cat <<EOF
DESCRIPTION
       Use openops.sh to install, update and interact with OpenOps.
       Visit https://docs.openops.com for more information.

SCRIPTS
       Install or update OpenOps (docker-compose):
              curl -fsS https://openops.sh/install | sh
       Upload and share docker logs:
              curl -fsS https://openops.sh/share-logs | sh
EOF

